"use client";
import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowUp, ArrowUpRight, Check, Code2, Copy, Download, Link2, Menu, X } from "lucide-react";
import type { ProjectCaseStudy } from "@/data/projects";
import { allTools, portfolioContent, projectAccents } from "@/data/portfolio";
import { profileData } from "@/data/profile";
import InteractiveCLI from "@/components/InteractiveCLI";
import HATopology from "@/components/HATopology";
const fadeUp = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: 0.75, ease: [0.22, 1, 0.36, 1] as const } } };
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={`reveal ${className}`.trim()} variants={fadeUp} initial={reduceMotion ? false : "hidden"} whileInView="show" viewport={{ once: true, amount: 0.14, margin: "0px 0px -8% 0px" }} transition={{ delay }}>{children}</motion.div>;
}
function StatusDot({ label = "Available for work" }: { label?: string }) { return <span className="status-line"><span className="status-dot" />{label}</span>; }
const heroStatementLines = [
  "I am a network security engineer",
  "working across enterprise networks,",
  "cybersecurity, and the packet on the",
  "wire.",
];
function HeroStatement() {
  const reduceMotion = useReducedMotion();
  return <h1 id="hero-heading" className="hero-statement">{heroStatementLines.map((line, index) => <span className="hero-statement__line" key={line}><motion.span className="hero-statement__line-inner" initial={reduceMotion ? false : { opacity: 0, y: "105%" }} animate={reduceMotion ? undefined : { opacity: 1, y: 0 }} transition={reduceMotion ? undefined : { delay: 0.22 + index * 0.1, duration: 0.72, ease: [0.22, 1, 0.36, 1] }}>{line}</motion.span></span>)}</h1>;
}
function NetworkArtwork({ accent }: { accent: string }) {
  return <div className="network-art" style={{ "--accent": accent } as React.CSSProperties} aria-hidden="true">
    <div className="network-art__topline"><span>live trace / 03</span><span>all systems nominal</span></div>
      <svg viewBox="0 0 760 520" role="presentation">
      <defs><filter id="glow"><feGaussianBlur stdDeviation="5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
      <path className="network-path" d="M92 356 C178 244, 204 162, 320 202 S472 390, 612 176" />
      <path className="network-path network-path--secondary" d="M122 422 C208 350, 274 332, 366 348 S510 256, 640 300" />
      <path className="network-path network-path--tertiary" d="M96 110 C248 136, 252 272, 402 222 S512 122, 668 112" />
      <g className="network-nodes" filter="url(#glow)"><circle cx="92" cy="356" r="8" /><circle cx="320" cy="202" r="7" /><circle cx="612" cy="176" r="10" /><circle cx="122" cy="422" r="5" /><circle cx="366" cy="348" r="7" /><circle cx="640" cy="300" r="6" /><circle cx="96" cy="110" r="6" /><circle cx="402" cy="222" r="8" /><circle cx="668" cy="112" r="7" /></g>
      <g className="network-labels"><text x="66" y="386">client / en0</text><text x="288" y="178">tunnel / tun0</text><text x="566" y="154">gateway / vip</text><text x="570" y="332">vrrp / 01</text></g>
    </svg>
    <div className="network-art__footer"><span>packet path visualization</span><span>0 leaks observed</span></div>
  </div>;
}
function AppNav({ onMenu, onContact }: { onMenu: () => void; onContact: () => void }) {
  const reduceMotion = useReducedMotion();
  return <motion.header className="site-header" initial={reduceMotion ? false : { opacity: 0, y: -10 }} animate={reduceMotion ? undefined : { opacity: 1, y: 0 }} transition={reduceMotion ? undefined : { duration: 0.55, ease: [0.22, 1, 0.36, 1] }}><a className="wordmark" href="#top" aria-label="Shuraim Bhat home">shuraim.b</a><nav className="desktop-nav" aria-label="Primary navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#lab">Lab</a></nav><button className="nav-contact" onClick={onContact}>Contact <ArrowUpRight size={14} /></button><button className="menu-toggle" onClick={onMenu} aria-label="Open menu"><Menu size={17} /></button></motion.header>;
}
function MobileMenu({ onClose, onContact }: { onClose: () => void; onContact: () => void }) {
  return <motion.div className="mobile-menu" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="mobile-menu__inner"><button className="mobile-menu__close" onClick={onClose} aria-label="Close menu"><X size={18} /></button><span className="eyebrow">Navigation / 00</span><a href="#work" onClick={onClose}>Work <ArrowUpRight size={22} /></a><a href="#about" onClick={onClose}>About <ArrowUpRight size={22} /></a><a href="#lab" onClick={onClose}>Lab <ArrowUpRight size={22} /></a><button className="mobile-menu__contact" onClick={() => { onClose(); onContact(); }}>Contact <ArrowUpRight size={22} /></button></div></motion.div>;
}
function CaseStudyPanel({ study, onClose }: { study: ProjectCaseStudy; onClose: () => void }) {
  return <motion.div className="case-study-layer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <motion.aside className="case-study-panel" role="dialog" aria-modal="true" aria-labelledby="case-study-heading" initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>
      <div className="case-study-panel__header"><span className="eyebrow">Case study / {study.number}</span><button onClick={onClose}>Close <X size={14} /></button></div>
      <div className="case-study-panel__body"><div className="case-study-panel__intro"><h2 id="case-study-heading">{study.title}</h2><p>{study.subtitle}</p></div><div className="case-study-panel__grid"><div><span className="eyebrow">Context</span><p>{study.context}</p></div><div><span className="eyebrow">The problem</span><p>{study.problem}</p></div></div><div className="case-study-panel__approach"><span className="eyebrow">Approach / three planes</span>{study.technicalApproach.map((plane, index) => <article key={plane.title}><span>0{index + 1}</span><div><h3>{plane.title}</h3><p>{plane.details.join(" ")}</p></div></article>)}</div><div className="case-study-panel__results"><span className="eyebrow">Measured result</span>{study.measurableResults.map((result) => <div key={result.metric}><strong>{result.metric}</strong><p>{result.description}</p></div>)}</div>{study.sampleTraceSnippet && <pre className="case-study-panel__code">{study.sampleTraceSnippet.code}</pre>}</div>
    </motion.aside>
  </motion.div>;
}
function ContactPanel({ onClose }: { onClose: () => void }) {
  const [mode, setMode] = useState<"Opportunity" | "Message">("Opportunity");
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const [focus, setFocus] = useState<string | null>(null);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const subject = mode === "Opportunity" ? "Network security opportunity" : "Message for Shuraim";
    const body = `Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`;
    window.location.href = `mailto:${profileData.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };
  return <motion.div className="contact-layer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <motion.aside className="contact-panel" role="dialog" aria-modal="true" aria-labelledby="contact-panel-heading" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}>
      <div className="contact-panel__header"><div className="contact-panel__modes" role="tablist" aria-label="Contact mode"><button className={mode === "Opportunity" ? "is-selected" : ""} onClick={() => setMode("Opportunity")} role="tab" aria-selected={mode === "Opportunity"}><span className="radio-mark" />Opportunity</button><button className={mode === "Message" ? "is-selected" : ""} onClick={() => setMode("Message")} role="tab" aria-selected={mode === "Message"}><span className="radio-mark" />Message</button></div><button className="contact-panel__close" onClick={onClose}>Close</button></div>
      <div className="contact-panel__body"><span className="eyebrow">Start a conversation</span><h2 id="contact-panel-heading">{mode === "Opportunity" ? "Let’s build something dependable." : "Send a quick note."}</h2><form onSubmit={submit}>
        {mode === "Opportunity" && <fieldset><legend>What are you reaching out about? <span>You can select multiple</span></legend><div className="check-row"><label><input type="checkbox" /> <span>Security engineering</span></label><label><input type="checkbox" /> <span>Infrastructure</span></label><label><input type="checkbox" /> <span>QA / testing</span></label></div></fieldset>}
        <label className={`field ${focus === "name" ? "is-focused" : ""}`}><span>What’s your name?</span><input required value={form.name} onFocus={() => setFocus("name")} onBlur={() => setFocus(null)} onChange={(event) => update("name", event.target.value)} /></label>
        <label className={`field ${focus === "email" ? "is-focused" : ""}`}><span>What’s your email?</span><input required type="email" value={form.email} onFocus={() => setFocus("email")} onBlur={() => setFocus(null)} onChange={(event) => update("email", event.target.value)} /></label>
        <label className={`field field--message ${focus === "message" ? "is-focused" : ""}`}><span>{mode === "Opportunity" ? "Tell me about the role or project" : "What’s on your mind?"}</span><textarea required rows={3} value={form.message} onFocus={() => setFocus("message")} onBlur={() => setFocus(null)} onChange={(event) => update("message", event.target.value)} /></label>
        <button className="contact-panel__send" type="submit"><span>Send</span><ArrowUpRight size={16} /></button>
      </form></div>
    </motion.aside>
  </motion.div>;
}
export default function Home() {
  const [activeProject, setActiveProject] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [contactOpen, setContactOpen] = useState(false);
  const [caseStudyOpen, setCaseStudyOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [scrollProgress, setScrollProgress] = useState(0);
  const reduceMotion = useReducedMotion();
  const { projects: caseStudies, experience: experiencesData } = portfolioContent;
  const activeStudy = caseStudies[activeProject];
  const projectAccent = projectAccents[activeProject % projectAccents.length];
  useEffect(() => { const onScroll = () => setScrollProgress(Math.min(window.scrollY / Math.max(document.body.scrollHeight - window.innerHeight, 1), 1)); window.addEventListener("scroll", onScroll, { passive: true }); onScroll(); return () => window.removeEventListener("scroll", onScroll); }, []);
  const copyEmail = async () => { await navigator.clipboard?.writeText(profileData.email); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <div className="site-shell" id="top"><div className="grain" aria-hidden="true" /><AppNav onMenu={() => setMenuOpen(true)} onContact={() => setContactOpen(true)} /><AnimatePresence>{menuOpen && <MobileMenu onClose={() => setMenuOpen(false)} onContact={() => setContactOpen(true)} />}</AnimatePresence><AnimatePresence>{contactOpen && <ContactPanel onClose={() => setContactOpen(false)} />}</AnimatePresence><AnimatePresence>{caseStudyOpen && <CaseStudyPanel study={activeStudy} onClose={() => setCaseStudyOpen(false)} />}</AnimatePresence>
    <main>
      <section className="hero section-grid" aria-labelledby="hero-heading"><div className="hero__rail"><motion.div className="hero__portrait" aria-hidden="true" initial={reduceMotion ? false : { opacity: 0, scale: .94 }} animate={reduceMotion ? undefined : { opacity: 1, scale: 1 }} transition={reduceMotion ? undefined : { delay: .12, duration: .7, ease: [0.22, 1, 0.36, 1] }}><span>SSB</span></motion.div><motion.div className="hero__rail-footer" initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={reduceMotion ? undefined : { opacity: 1, y: 0 }} transition={reduceMotion ? undefined : { delay: .72, duration: .55 }}><small>Services:</small><strong>Network security<br />Cybersecurity</strong></motion.div></div><div className="hero__body"><motion.div className="hero__intro-marker" aria-hidden="true" initial={reduceMotion ? false : { opacity: 0, x: -8 }} animate={reduceMotion ? undefined : { opacity: 1, x: 0 }} transition={reduceMotion ? undefined : { delay: .28, duration: .5 }}><span className="hero__marker-dot" /><span className="hero__marker-arrow">↳</span></motion.div><HeroStatement /><motion.div className="hero__footer" initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={reduceMotion ? undefined : { opacity: 1, y: 0 }} transition={reduceMotion ? undefined : { delay: .76, duration: .6 }}><span><small>Elsewhere:</small><br /><strong>LinkedIn / GitHub</strong></span><span><small>Available for work:</small><br /><strong>September ‘26</strong></span><a className="scroll-cue" href="#work">Scroll <ArrowDown size={15} /></a></motion.div></div></section>
      <section className="work-section section-grid" id="work" aria-labelledby="work-heading"><div className="section-rail"><span className="eyebrow">Selected work / 01</span><span className="section-number">0{activeProject + 1}/0{caseStudies.length}</span></div><div className="work__main"><Reveal className="section-heading-row"><h2 id="work-heading">Built for the<br /><em>failure path.</em></h2><a href="#project-list">View all work <ArrowUpRight size={15} /></a></Reveal><Reveal delay={0.08}><motion.div className="project-stage" whileHover={reduceMotion ? undefined : { scale: 1.004 }} transition={{ duration: 0.35, ease: "easeOut" }}><NetworkArtwork accent={projectAccent} /><div className="project-stage__caption"><span>{activeStudy.category}</span><span>{activeStudy.period}</span></div></motion.div></Reveal><div className="project-details"><Reveal><div className="project-details__title"><span className="eyebrow">0{activeProject + 1} / {activeStudy.role}</span><h3>{activeStudy.title}</h3><p>{activeStudy.subtitle}</p></div></Reveal><Reveal delay={0.08}><div className="project-details__aside"><span className="eyebrow">What changed</span><strong>{activeStudy.measurableResults[0].metric}</strong><p>{activeStudy.measurableResults[0].description}</p><button onClick={() => setCaseStudyOpen(true)}>Read case study <ArrowUpRight size={14} /></button></div></Reveal></div><Reveal className="project-switcher-reveal" delay={0.16}><div className="project-switcher" id="project-list" role="tablist" aria-label="Project selector">{caseStudies.map((study, index) => <button key={study.id} className={index === activeProject ? "is-active" : ""} onClick={() => setActiveProject(index)} role="tab" aria-selected={index === activeProject}>{index === activeProject && <motion.span className="project-switcher__indicator" layoutId="active-project-indicator" transition={{ type: "spring", stiffness: 380, damping: 32 }} />}<span>0{index + 1}</span>{study.title}</button>)}</div></Reveal></div></section>
      <section className="about-section section-grid" id="about" aria-labelledby="about-heading"><div className="section-rail"><span className="eyebrow">About / 02</span><span>01 / 04</span></div><div className="about__main"><Reveal><h2 id="about-heading">The work lives<br />between <em>layers.</em></h2></Reveal><div className="about__columns"><Reveal className="about-column about-column--lead" delay={0.06}><p className="about__lead">I am a Network Security Engineer at WiJungle, working where production infrastructure, packet-level debugging, and usable tools meet.</p></Reveal><Reveal className="about-column" delay={0.12}><p>I enjoy the unglamorous parts: tracing a dropped connection across three planes, finding the stale socket, and making the next release feel a little more dependable than the last.</p><a className="text-link" href={profileData.linkedin} target="_blank" rel="noreferrer">More on LinkedIn <ArrowUpRight size={15} /></a></Reveal></div><div className="proof-row">{profileData.proofPoints.map((point, index) => <Reveal key={point.metric} delay={index * 0.06}><div className="proof-card"><span>{point.label}</span><strong>{point.metric}</strong><p>{point.detail}</p></div></Reveal>)}</div></div></section>
      <section className="experience-section section-grid" aria-labelledby="experience-heading"><div className="section-rail"><span className="eyebrow">Experience / 03</span><span>timeline</span></div><div className="experience__main"><Reveal><div className="section-heading-row"><h2 id="experience-heading">A record of<br /><em>staying curious.</em></h2><span className="muted-note">Selected roles &amp; responsibilities</span></div></Reveal><div className="experience-list">{experiencesData.map((item, index) => <Reveal key={item.id} delay={index * 0.05}><article className="experience-item"><div className="experience-item__date">{item.period}<br /><span>{item.type}</span></div><div className="experience-item__content"><div><h3>{item.role}</h3><p>{item.company} / {item.location}</p></div><p className="experience-item__summary">{item.summary}</p><div className="tag-list">{item.technologies.slice(0, 5).map((tech) => <span key={tech}>{tech}</span>)}</div></div></article></Reveal>)}</div></div></section>
      <section className="lab-section section-grid" id="lab" aria-labelledby="lab-heading"><div className="section-rail"><span className="eyebrow">Lab / 04</span><span>observations</span></div><div className="lab__main"><Reveal><div className="section-heading-row"><h2 id="lab-heading">Proofs from the<br /><em>control plane.</em></h2><span className="muted-note">Interactive network security lab</span></div></Reveal><div className="lab-grid"><Reveal delay={0.06}><motion.div className="terminal-card" whileHover={reduceMotion ? undefined : { y: -3 }} transition={{ duration: 0.3, ease: "easeOut" }}><div className="terminal-card__bar"><span /><span /><span /><label>verification.log</label></div><pre>{"$ trace --interface tun0 --runs 500\n[ok] tunnel created       500/500\n[ok] route teardown       500/500\n[ok] physical egress      0 leaks\n[ok] vrrp promotion       0.82s\nstatus: clean handoff"}</pre></motion.div></Reveal><Reveal delay={0.12}><motion.div className="tool-wall" whileHover={reduceMotion ? undefined : { y: -3 }} transition={{ duration: 0.3, ease: "easeOut" }}><span className="eyebrow">Security &amp; network tools</span><div>{allTools.map((tool) => <span key={tool}>{tool}</span>)}</div><a className="text-link" href={profileData.resume.docxUrl} download>Download résumé <Download size={14} /></a></motion.div></Reveal></div><Reveal delay={0.18}><HATopology /></Reveal><Reveal delay={0.24}><div className="lab-cli"><div className="lab-cli__intro"><span className="eyebrow">Interactive shell</span><p>Query a sanitized appliance lab trace. Try <code>help</code>, <code>trace</code>, or <code>skills</code>.</p></div><InteractiveCLI /></div></Reveal></div></section>
      <section className="contact-section section-grid" id="contact" aria-labelledby="contact-heading"><div className="section-rail"><span className="eyebrow">Contact / 05</span><span>say hello</span></div><div className="contact__main"><Reveal><h2 id="contact-heading">Have a problem<br />worth <em>solving?</em></h2></Reveal><div className="contact__row"><Reveal delay={0.08}><div><p className="contact__intro">I’m open to conversations about network security engineering, infrastructure reliability, and the systems behind both.</p><div className="contact__links"><a href={`mailto:${profileData.email}`}>{profileData.email} <ArrowUpRight size={15} /></a><button onClick={copyEmail}>{copied ? <Check size={14} /> : <Copy size={14} />} {copied ? "Copied" : "Copy email"}</button></div></div></Reveal><Reveal delay={0.14}><div className="social-links"><a href={profileData.linkedin} target="_blank" rel="noreferrer"><Link2 size={15} /> LinkedIn <ArrowUpRight size={14} /></a><a href={profileData.github} target="_blank" rel="noreferrer"><Code2 size={15} /> GitHub <ArrowUpRight size={14} /></a></div></Reveal></div></div></section>
    </main>
    <footer className="site-footer"><span>© {new Date().getFullYear()} Shuraim Shakeel Bhat</span><StatusDot label="Built with care / no shortcuts" /><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Back to top <ArrowUp size={14} /></button></footer><div className="scroll-progress" style={{ transform: `scaleX(${scrollProgress})` }} />
  </div>;
}
